# Generated by Django 4.0.3 on 2022-04-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Pirate',
        ),
    ]
